default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
      - id: reorder-python-imports
        args:
          - --py3-plus
          - --application-directories=.:src
        exclude: migrations/
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
        exclude: migrations/
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.4.0
    hooks:
      - id: django-upgrade
        args:
          - --target-version=4.0
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      -   id: yesqa
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.5
    hooks:
      -   id: pycln
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: |
          (?x)^(
              .*/migrations/.*
          )$
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-tidy-imports
          - flake8-print
        args: [--max-line-length=120]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.25.0
    hooks:
      - id: eslint
        args: [--fix]
        additional_dependencies:
        - "eslint@8.25.0"
        - "eslint-plugin-prettier@4.2.1"
        - "eslint-config-standard@17.0.0"
        - "eslint-plugin-import@2.26.0"
        - "eslint-plugin-n@15.3.0"
        - "eslint-plugin-promise@6.1.0"
